A/A/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account')),
    path('irisa/',include('irisa.urls',namespace='irisa')),
]

A/account/urls.py
from django.urls import path
from . import views


app_name='account'
urlpatterns=[
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('login/',views.UserLoginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
    path('profile/<int:user_id>/',views.UserProfileView.as_view(),name='user_profile'),
    path('reset/',views.UserPasswordResetView.as_view(),name='reset_password'),
    path('reset_done/',views.UserPasswordResetDoneView.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('confirm/complete/',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('follow/<int:user_id>/',views.UserFollowView.as_view(),name='user_follow'),
    path('unfollow/<int:user_id>/',views.UserUnfollowView.as_view(),name='user_unfollow'),
    path('edit_profile/',views.EditProfileProfileView.as_view(),name='edit_profile'),
]

A/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>',views.PostView.as_view(),name='post_detail'),
    path('post/delete/<int:post_id>/',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/update/<int:post_id>/',views.PostUpdateView.as_view(),name='post_update'),
    path('post/new/',views.NewPostView.as_view(),name='post_new'),
    path('reply/<int:post_id>/<int:comment_id>/',views.PostAddReplyView.as_view(),name='add_reply'),
    path('like/<int:post_id>/',views.PostLikeView.as_view(),name='post_like'),
]

A/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    title = models.TextField()
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta: #this class is for order by a field this model completely
        ordering = ('-created','title')


    def __str__(self) -> str: # این متد برای این است که در ادمین پنل فیلد تایتل را در لیست پست ها ببینیم
        return self.title

    def get_absolute_url(self):
        return reverse('home:post_detail',args=(self.id,self.slug))
    
    def likes_count(self):
        return self.pvote.count()
    
    def user_can_like(self,user):
        user_like = user.uvotes.filter(post=self)
        if user_like.exists():
            return True
        else:
            return False

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='ucomments')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='pcomments')
    reply = models.ForeignKey('Comment',on_delete=models.CASCADE,related_name='rcomment',blank=True,null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'
    
class Vote(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='uvotes')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='pvote')
    
    def __str__(self):
        return f'{self.user} like {self.post.slug}'
    

A/home/forms.py
from django import forms
from .models import Post,Comment

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body',)

class PostNewForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body',)

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets={
            'body':forms.Textarea(attrs={'class':'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets={
            'body':forms.Textarea(attrs={'class':'form-control'})
        }

class PostSearchForm(forms.Form):
    search = forms.CharField()

A/home/views.py
from typing import Any
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.views import View
from .models import Post,Comment,Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostUpdateForm,PostNewForm,CommentCreateForm,CommentReplyForm,PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.


class HomeView(View):
    form_class = PostSearchForm

    def get(self,request):
        #posts = Post.objects.all().order_by('-created')
        posts = Post.objects.order_by('-created')
        if request.GET.get('search'):
            posts=posts.filter(body__contains=request.GET['search']) #part 40-search
        return render(request,'home/index.html',{'posts':posts,'form':self.form_class})
    

class PostView(View):
    login_url='/account/login'
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm
    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.post_instance = get_object_or_404(Post,pk=kwargs['post_id'],slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)
    

    def get(self,request,post_id,post_slug):
        #post = Post.objects.get(pk=post_id)
        post = get_object_or_404(Post,pk=post_id)
        comments = self.post_instance.pcomments.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like=True
        return render(request,'home/detail.html',{'post':self.post_instance,'comments':comments,'form':self.form_class,
                                                  'reply_form':self.form_class_reply,'can_like':can_like})
    
    @method_decorator(login_required) #part 36 method decorators
    def post( self,request,*args,**kwargs):

        form=self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request,'comment added successfully','success')
            return redirect('home:post_detail',self.post_instance.id,self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin,View):
    login_url='/account/login'
    def get(self,request,post_id):
         #post = Post.objects.get(id=post_id)
         post = get_object_or_404(Post,pk=post_id)
         if request.user.id == post.user.id:
             post.delete()
             messages.success(request,'پست بطور کامل پاک شد.','info')
             return redirect('home:home')
         messages.error(request,'شما نمی توانید این پست را حذف کنید.','danger')
         return redirect('home:home')
    

class PostUpdateView(LoginRequiredMixin,View):
     form_class  = PostUpdateForm

     def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
         #self.post_instance= Post.objects.get(pk=kwargs['post_id'])
         self.post_instance = get_object_or_404(Post,pk=kwargs['post_id'])
         return super().setup(request, *args, **kwargs)
     
     def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
         post = self.post_instance
         if not post.user.id == request.user.id:
             messages.error(request,'access denied','danger')
             return redirect('home:home')
         return super().dispatch(request, *args, **kwargs)
     

     def get(self,request,post_id):
         post = self.post_instance
         form = self.form_class(instance=post)
         return render(request,'home/update.html',{'form':form})

     def post(self,request,post_id):
         post = self.post_instance
         form=self.form_class(request.POST,instance=post)
         if form.is_valid:
             updated_post = form.save(commit=False)
             updated_post.slug = slugify(form.cleaned_data['title'][:30])
             updated_post.save()
             messages.success(request,'بروز رسانی شد','success')
             return render(request,'home/detail.html',{'post':post})
         


class NewPostView(LoginRequiredMixin,View):
    form_class = PostNewForm

    def get(self,request):
        form = self.form_class
        return render(request,'home/new.html',{'form':form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid:
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['title'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request,'پست اضافه شد','success')
            return redirect('home:post_detail',new_post.id,new_post.slug)
        
         
class PostAddReplyView(LoginRequiredMixin,View):
    form_class = CommentReplyForm

    def post(self,request,post_id,comment_id):
        post = get_object_or_404(Post,id=post_id)
        comment = get_object_or_404(Comment,pk=comment_id)
        form=self.form_class(request.POST)
        if form.is_valid():
            reply=form.save(commit=False)
            reply.user=request.user
            reply.post = post
            reply.reply = comment
            reply.is_replu = True
            reply.save()
            messages.success(request,'reply submited successfully','success')
        return redirect('home:post_detail',post.id,post.slug)

class PostLikeView(LoginRequiredMixin,View):
    def get(self,request,post_id):
        post = get_object_or_404(Post,pk=post_id)
        like = Vote.objects.filter(post = post,user=request.user)
        if like.exists():
            messages.error(request,'you already liked this post.','danger')
        else:
            Vote.objects.create(post=post,user=request.user)
            messages.success(request,'you like this post successfully')
        return redirect('home:post_detail', post.id,post.slug)
    

    
        
    

A/home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="d-flex card-header">
            <div>
                <a class="btn btn-info" href="{% url 'account:user_profile' post.user.id %}">{{ post.user.username }}</a>
            </div>
            <div>
                <small class="card">Created at: {{ post.created|date:'D_Y/m/j' }}</small><small class="card">Last Update: {{ post.updated|date:'D_Y/m/j' }}</small>
                
            </div>   

        </div>
        <div class="card-body">
            <div class="card-title">
                <h3>{{ post.title }}</h3>
            </div>
            <div class="card-text">
                <h6>{{ post.body }}</h6>
            </div>
                <a href="{% url 'home:post_like' post.id %}" class="btn btn-primary col-md-2 {% if can_like %}disabled{% endif %}">Like {{ post.likes_count }}</a>

                {% if request.user.id == post.user.id %}
                    <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">حذف</a>
                    <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">اصلاح</a>
                {% endif %} 
            <hr>
                {% if request.user.is_authenticated %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Send" class="btn btn-primary">
                    </form>
                {% else %}
                    <p class="alert alert-danger">only loged in user can write comment.</p>
                {% endif %}
            <hr>
            <p>{{ comments.count }} Comments</p>
            {% for comment in comments %}
                <div class="card">
                    <p class="card-header bg-dark text-white">{{ comment.user }} | {{ comment.created }}</p>
                    <p class="card-body">{{ comment.body }}</p>
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'home:add_reply' post.id comment.id %}" method="post" style="margin: 10px;">
                            {% csrf_token %}
                            {{ reply_form.as_p }}
                            <input type="submit" value="Send" class="btn btn-primary">
                        </form>
                    {% endif %}
                    {% for reply in comment.rcomment.all %}
                        <div class="card"  style="margin: 10px;">
                            <p class="card-header bg-dark text-white">{{ reply.user }} | {{ reply.created }}</p>
                            <p class="card-body">{{ reply.body }}</p>
                        </div>
                    {% endfor %}
                </div>
                <br>
            {% empty %}
                <div>
                    <p>No comment yet!</p>
                </div>
            {% endfor %}
        </div>
        
    </div>
    
{% endblock %}

A/home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form><br>

<div class="card">
    {% for post in posts %}
        <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.title }} <br> ({{ post.created }})</a>
        <!-- <a href="{% url 'home:post_detail' post.id  post.slug%}" class="card-body">{{ post.title }} <br> ({{ post.created }})</a> -->
        <hr>
    {% endfor %}
</div>
{% endblock %}

A/home/templates/home/new.html
{% extends 'base.html' %}

{% block content %}
     <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="New Post">
     </form>
{% endblock %}

A/home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}